version: '3'

services:
  wordpress:
    container_name: wordpress
    image: jhonpedro/wordpress:5.7
    ports:
      - 9000:9000
    volumes:
      - ./wordpress:/var/www/wordpress

  nginx:
    container_name: nginx
    image: nginx:1.19-alpine
    ports:
      - 80:80
    volumes:
      - ./wordpress:/var/www/wordpress
      - ./site.conf:/etc/nginx/conf.d/default.conf
  mysql:
    container_name: mysql_wordpress
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=codecon
    ports:
      - 3306:3306
